### ISSUE TITLE
Streamlit app - waiting on user input in the background

### ISSUE THREAD

**Issue by michalmar** [yanivvak/dream-team#3]
When run is finishing, the app hangs as it waits for the user reply:

<img width="842" alt="image" src="https://github.com/yanivvak/dream-team/assets/16072588/61f1d078-8cde-4de3-8684-347907c57dd4">

**Comment by yanivvak** [comment]
At the moment it prints the output in the end(you should type exit), a possible feature is to print the conversation in Streamlit Ui instead of the terminal, would you like to contribute? :-)

**Comment by michalmar** [comment]
Yes, why not!

**Comment by michalmar** [comment]
I added PR with this improvement https://github.com/yanivvak/dream-team/pull/9

**Comment by michalmar** [comment]
closing now
