### ISSUE TITLE
OAI_CONFIG_LIST for Azure

### ISSUE THREAD

**Issue by michalmar** [yanivvak/dream-team#4]
In your guide to fill the OAI_CONFIG_LIST is a wron instruction to include `api_base` but then it complaints, but the apparently  correct value is `azure_endpoint`

**Comment by yanivvak** [comment]
Thank you!
Please check your version,
Here's Autogen documentation for azure open ai:
https://github.com/microsoft/autogen/blob/c221eea14e0acba569066718bbfeba75fa80aa54/OAI_CONFIG_LIST_sample#L4
